### ISSUE TITLE
[CTF] Utilities

### ISSUE THREAD

**Issue by abdilahrf** [zbetcheckin/Security_list#3]
Scrape writeup from ctftime `https://github.com/abdilahrf/CTFWriteupScrapper`

**Comment by zbetcheckin** [comment]
Hi abdilahrf,
Thanks for this issue and your project looks great. I mostly add list of tools or list of list with few exceptions. I think that your project has his place in the awesome-ctf repo which is already linked here : https://github.com/apsdehal/awesome-ctf. This awesome-ctf repo is a list of Capture The Flag (CTF) frameworks, libraries, resources, softwares and tutorials.
