### ISSUE TITLE
Recommend a webshell management tool

### ISSUE THREAD

**Issue by WangYihang** [zbetcheckin/Security_list#4]
A webshell manager via terminal
Simple Usage : https://asciinema.org/a/130893

> https://github.com/WangYihang/Webshell-Sniper

**Comment by zbetcheckin** [comment]
Hi WangYihang,
Thanks for this issue, I saw that your project is already present in the awesome-web-hacking : 
https://github.com/infoslack/awesome-web-hacking. 
This awesome list is already linked here and I do not prefer to duplicate your project. I mostly add list of tools or list of list with few exceptions. Nice tool by the way.
